name: CI

on:
  push:
    branches: [ master ]

jobs:
  push-to-company:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your personal repo
      - name: Checkout personal repo
        uses: actions/checkout@v3

      - name: Debug secret
        run: |
          if [ -z "${COMPANY_TOKEN}" ]; then
            echo "Token is empty!"
          else
            echo "Token is set."
          fi
        env:
          COMPANY_TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }} 

      # Step 2: Configure Git (needed for pushes)
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Add company repo as remote
      - name: Add company repo
        env:
          COMPANY_TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          git remote add company https://x-access-token:${COMPANY_TOKEN}@github.com/supplycraftkakod/kakud-agri.git
          git fetch company

      # Step 4: Push to company repo
      - name: Push changes
        env:
          COMPANY_TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          git push company HEAD:master
