name: Sync to Company Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug URL
        run: echo "https://x-access-token:***@github.com/supplycraftkakod/kakud-agri.git"

      - name: Push to company repo
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          BRANCH=$(git branch --show-current)
          git remote add company https://x-access-token:${{ secrets.COMPANY_REPO_TOKEN }}@github.com/supplycraftkakod/kakud-agri.git
          git push company $BRANCH:$BRANCH --force