name: Sync to Company Repo

on:
  push:
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Debug URL
        run: |
          echo "URL: https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git"
          git remote -v
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}

      - name: Test access to company repo
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          git ls-remote https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git

      - name: Push to company repo
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          git remote add company https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git
          git push company master --force