name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_PAT }}

      - name: Add company repo as remote
        run: |
          git remote add company https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git
          git fetch company
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}

      - name: Push to company repo
        run: |
          git push company HEAD:master --force
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}