name: CI

on:
  push:
    branches: [ master ]

jobs:
  push-to-company:
    runs-on: ubuntu-latest

    steps:
      # Checkout the company repo directly using PAT
      - name: Checkout company repo
        uses: actions/checkout@v3
        with:
          repository: supplycraftkakod/kakud-agri
          token: ${{ secrets.COMPANY_REPO_TOKEN }}
          ref: master

      # Configure Git for commits
      - name: Configure Git
        run: |
          git config user.name "CI Bot"
          git config user.email "ci-bot@users.noreply.github.com"

      - name: Clone personal repo
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_REPO_TOKEN }}@github.com/abulKhasim/Kakud.git personal-repo

      # Copy files from personal repo to company repo
      - name: Copy files
        run: |
          cp -R personal-repo/* .
          cp -R personal-repo/.* . 2>/dev/null || true
          rm -rf personal-repo/.git  # only delete the personal repo .git folder

      # Commit changes if any
      - name: Commit changes
        run: |
          git add .
          git commit -m "CI update" || echo "No changes to commit"

      # Push back to company repo
      - name: Push changes
        run: git push company HEAD:master
