name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repo
      - name: Checkout current repo
        uses: actions/checkout@v3

      # Step 2: Clone or fetch the private repo using PAT
      - name: Clone private kakud-agri repo
        run: |
          # Option A: If you just need files from kakud-agri, clone fresh
          git clone https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git kakud-agri

          # Option B: If you need to fetch/update it into an existing folder
          # git remote add kakud-agri https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git
          # git fetch kakud-agri
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
