name: Sync to Company Repo

on:
  push:
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show current branch
        run: echo "Current branch is $(git branch --show-current)"

      - name: Push to company repo
        run: |
          BRANCH=$(git branch --show-current)
          git remote add company https://x-access-token:${{ secrets.COMPANY_REPO_TOKEN }}git@github.com:supplycraftkakod/kakud-agri.git
          git push company HEAD:$BRANCH --force
