name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add company repo as remote
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          git remote add company https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git
          git fetch company

      - name: Push to company repo
        run: |
          git push company HEAD:master --force
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}