name: CI

on:
  push:
    branches: [ master ]

jobs:
  push-to-company:
    runs-on: ubuntu-latest

    steps:
      # Checkout the company repo directly using PAT
      - name: Checkout company repo
        uses: actions/checkout@v3
        with:
          repository: supplycraftkakod/kakud-agri
          token: ${{ secrets.COMPANY_REPO_TOKEN }}
          ref: master

      # Configure Git for commits
      - name: Configure Git
        run: |
          git config user.name "CI Bot"
          git config user.email "ci-bot@users.noreply.github.com"

      - name: Copy files from personal repo
        run: |
          cp -R ../<Kakud>/* .
          # Optionally remove .git folder from copied repo if present
          rm -rf .git

      # Commit changes if any
      - name: Commit changes
        run: |
          git add .
          git commit -m "CI update" || echo "No changes to commit"

      # Push back to company repo
      - name: Push changes
        run: git push origin HEAD:master
