name: Sync to Company Repo

on:
  push:
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Test token scope
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          curl -H "Authorization: token ${TOKEN}" https://api.github.com/repos/supplycraftkakod/kakud-agri

      - name: Test access to company repo
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          git ls-remote https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git

      - name: Push to company repo
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          git remote add company https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git
          git push company master --force