name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add company repo as remote
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          git remote add company https://x-access-token:${TOKEN}@github.com/supplycraftkakod/kakud-agri.git
          git fetch company

      - name: Push to company repo
        env:
          TOKEN: ${{ secrets.COMPANY_REPO_TOKEN }}
        run: |
          git push company HEAD:master --force
